### PR TITLE
Force symlinks to be absolute

### LINKED ISSUE #753: Fix `clone.test.ts` – can't find file `test-walk/folder/3.txt/`
## Problem

A clone test seems to be broken and can't find a file.

```sh
@inlang-git/client:test:  ✓ src/raw/tests/GitRefManager.test.ts  (4 tests) 33ms
@inlang-git/client:test: stdout | src/raw/tests/clone.test.ts > clone > should set up the remote tracking branch by default
@inlang-git/client:test: FilesystemError: ENOENT: No such file or directory, symlink '/src/raw/tests/fixtures/isomorphic-git/__tests__/__fixtures__/test-walk/folder/3.txt/'
@inlang-git/client:test:     at Object.symlink (file:///home/runner/work/inlang/inlang/source-code-git/fs/dist/implementations/memoryFs.js:132:23)
@inlang-git/client:test:     at FileSystem.writelink (file:///home/runner/work/inlang/inlang/source-code-git/client/node_modules/isomorphic-git/internal-apis.js:4841:17)
@inlang-git/client:test:     at /home/runner/work/inlang/inlang/source-code-git/client/node_modules/isomorphic-git/index.cjs:6146:28
@inlang-git/client:test:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
@inlang-git/client:test:     at async Promise.all (index 1404)
@inlang-git/client:test:     at /home/runner/work/inlang/inlang/source-code-git/client/node_modules/isomorphic-git/index.cjs:6118:7
@inlang-git/client:test:     at /home/runner/work/inlang/inlang/source-code-git/client/node_modules/isomorphic-git/index.cjs:987:16 {
@inlang-git/client:test:   code: 'ENOENT',
@inlang-git/client:test:   path: '/src/raw/tests/fixtures/isomorphic-git/__tests__/__fixtures__/test-walk/folder/3.txt/',
@inlang-git/client:test:   syscall: 'symlink',
@inlang-git/client:test:   target: undefined
@inlang-git/client:test: }
@inlang-git/client:test: 
```

### Expected behavior

Test should find the file.

Maybe it's because the 3.txt with a slash behind it is registered as a folder and not file? 
Only a wild guess.

## Steps to reproduce

run `npm run test`.

### PR DESCRIPTION
**Pull request by araknast**
All paths in memoryFs should be absolute, but isomorphic-git's `walk` fixture includes a relative symlink that causes subtle errors. This change ensures that all symlinks targets that do not begin with `/` are normalized relative to the basedir of the symlink.

Fixes #753

### CODE REVIEW

**Comment by samuelstroschein** [comment]
@araknast Are you confident that forcing absolute paths is the right decision?

File: source-code-git/fs/src/implementations/memoryFs.ts [hunk 1]
```diff
@@ -157,15 +157,17 @@ export function createMemoryFs(): NodeishFilesystem {
 			path: Parameters<NodeishFilesystem["symlink"]>[1],
 		) {
 			path = normalPath(path)
+			target = target.startsWith("/") ? target : `${path}/../${target}`
```
Comment (samuelstroschein) [inline source-code-git/fs/src/implementations/memoryFs.ts:160]: If we force absolute paths, wouldn't it make sense to use `assertIsAbsolutePath` and explicitly provide developers with a clear error message instead of implicitly fixing the path (that might lead to confusion because relative paths can sometimes be used and sometimes not)? 

Like in https://github.com/inlang/inlang/blob/3cc7b69936b393dfa6e3fc13a22b39e7734944ed/source-code-git/fs/src/utilities/fromJson.ts#L14

**Review by samuelstroschein — CHANGES_REQUESTED** [review]

File: source-code-git/fs/src/implementations/memoryFs.ts (hunk 1 above)
Comment (samuelstroschein) [reply source-code-git/fs/src/implementations/memoryFs.ts:160]: @araknast Are you confident that forcing absolute paths is the right decision?

EDIT: Absolute paths are less ambiguous for sure and cwd doesn't exist in the browser. Seems to me that trading off "works in every environment" for slight DX improvements for node (by not requiring absolute paths in node) is a good one.

Comment (araknast) [reply source-code-git/fs/src/implementations/memoryFs.ts:160]: > If we force absolute paths, wouldn't it make sense to use assertIsAbsolutePath and explicitly provide developers with a clear error message instead of implicitly fixing the path (that might lead to confusion because relative paths can sometimes be used and sometimes not)?

Ideally we would be able to use `assertIsAbsolutePath` to ensure all paths begin with `/` but I don't think it would be worth the trouble of making it work with isomorphic-git. There is also the issue of `mockEnvironment`, and the reason this issue exists in the first place in that symlinks on 'real' filesystems often use relative paths. Using `assertIsAbsolutePath` would mean that we could not create a mock environment with a directory that contains a relative symbolic link (the reason why the error in #753 was occurring.

> Are you confident that forcing absolute paths is the right decision?
>
> EDIT: Absolute paths are less ambiguous for sure and cwd doesn't exist in the browser. Seems to me that trading off "works in every environment" for slight DX improvements for node (by not requiring absolute paths in node) is a good one.

All paths in memoryFs are 'absolute' anyways since they are always relative to the root of the filesystem. Internally a '/' is prepended to the path as part of the `normalPath` function. The behavior is identical to node as if `cwd` was set to `/`. 

To be clear, I don't necessarily want to enforce use of absolute paths in the api (for the reasons outlined above), only to ensure all paths that are passed around internally in memoryFs are absolute. This was the intended behavior before, and this patch simply extends it to the `symlink` command.

Comment (samuelstroschein) [reply source-code-git/fs/src/implementations/memoryFs.ts:160]: @araknast Got it, makes sense!

**Review by samuelstroschein — APPROVED** [review]
@araknast feel free to merge!
